// Acciones para el login
export const REGISTRAR_USUARIO = 'REGISTRAR_USUARIO';
export const LOGIN_USUARIO = 'LOGIN_USUARIO';
export const SET_TOKEN = 'SET_TOKEN';
export const SET_USER = 'SET_USER';
export const UPDATE_CONFIG = 'UPDATE_CONFIG';
export const SET_TUTOR = 'SET_TUTOR';
export const SET_INCIDECIAS_TUTOR = 'SET_INCIDECIAS_TUTOR';
export const SET_ESTADO_EXTENSION = 'SET_ESTADO_EXTENSION';

// Registro de contenido ofensivo
export const OBTENER_REGISTRO = 'OBTENER_REGISTRO';
export const MODIFICAR_REGISTRO = 'MODIFICAR_REGISTRO';
export const OBTENER_CONTENIDO = 'OBTENER_CONTENIDO';
export const MODIFICAR_SEGMENTO = 'MODIFICAR_SEGMENTO';
export const SET_KEY = 'SET_KEY';

// Lista de excepciones y permitidas
export const OBTENER_PERMITIDAS = 'OBTENER_PERMITIDAS';
export const AGREGAR_PERMITIDAS = 'AGREGAR_PERMITIDAS';
export const ELIMINAR_PERMITIDA = 'ELIMINAR_PERMITIDA';
export const PERMITIDA_ACTUAL = 'PERMITIDA_ACTUAL';
export const OBTENER_NO_PERMITIDAS = 'OBTENER_NO_PERMITIDAS';
export const AGREGAR_NO_PERMITIDAS = 'AGREGAR_NO_PERMITIDAS';
export const ELIMINAR_NO_PERMITIDA = 'ELIMINAR_NO_PERMITIDA';
export const NO_PERMITIDA_ACTUAL = 'NO_PERMITIDA_ACTUAL';

// Acciones para el Dashboard
export const SET_INCIDECIAS_BY_WEEK = 'SET_INCIDECIAS_BY_WEEK';
export const SET_TIPO_INCIDECIAS_BY_DAY = 'SET_TIPO_INCIDECIAS_BY_DAY';
export const SET_NO_PERMITIDAS = 'SET_NO_PERMITIDAS';
export const GET_TIEMPO_CONEXION = 'GET_TIEMPO_CONEXION';
